VERSION: "inference_demo"
TRAINING_TYPE: 'coarse-fine'

FINE_MODEL_PATH: "/workspace/MR_checkpoints" # The path of the downloaded checkpoint directory.
CHECK_POINT_NAME: "fine_checkpoint.pth"
COARSE_MODEL_PATH: "/workspace/MR_checkpoints" # The path of the downloaded checkpoint directory.
COARSE_CHECK_POINT_NAME: "coarse_checkpoint.pth"

DATASET:
  BASE_DIR: '/workspace' # The path of the current project datasets directory.

VAL:
  IS_CROP: False
  TTA: False

INFERENCE:
  IS_OVERWRITE_PREDICT_MASK: True