VERSION: "inference_demo"
TRAINING_TYPE: 'coarse-fine'

FINE_MODEL_PATH: "/home/lichangrui/2024-1/checkpoints_dir/fine_checkpoint.pth" # The path of the downloaded checkpoint directory.
CHECK_POINT_NAME: "fine_checkpoint.pth"
COARSE_MODEL_PATH: "/home/lichangrui/2024-1/checkpoints_dir/coarse_checkpoint.pth" # The path of the downloaded checkpoint directory.
COARSE_CHECK_POINT_NAME: "coarse_checkpoint.pth"

DATASET:
  BASE_DIR: 'datasets' # The path of the current project datasets directory.

INFERENCE:
  IS_OVERWRITE_PREDICT_MASK: False

VAL:
  IS_CROP: False
  TTA: True


